:_basedir:
:_imagesdir: images/
:grid: cols
:development:

[[index]]

== Downloadsanchor:Downloads[]

To develop your own code to use or implement JDO, you can use the links below to download Apache JDO from an
official ASF download site. If you are using Maven, you can declare a dependency using the instructions below.

If you intend to develop JDO (make modifications to the JDO code), you should clone the
xref:source-code.adoc[public repository] and submit pull requests if desired.

Please see instruction below for xref:Verifying[verifying the integrity] of the
distribution files after downloading any artifacts.


=== Maven (convenience binary)anchor:Maven[]

The most convenient way to use JDO is to configure your project using Maven.
The JDO API can be downloaded
automatically by maven and placed into your local maven repository if you
include the proper dependency in your maven project definition.
For example:
[source,xml]
<dependency>
  <groupId>javax.jdo</groupId>
  <artifactId>jdo-api</artifactId>
  <version>3.2.1</version>
</dependency>

=== Source Downloads

[cols="18%,12%,20%,15%,20%,15%",options="header"]
|===
|Release Notes | Date | Sources .tar.gz | asc / sha | Sources .zip | asc / sha
| https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12351329&styleName=Html&projectId=10630[3.2.1]
| 2022-05-04
| https://www.apache.org/dyn/closer.lua/db/jdo/3.2.1/jdo-3.2.1-source-release.tar.gz[src.tar.gz (1.1 MB)]
| https://downloads.apache.org/db/jdo/3.2.1/jdo-3.2.1-source-release.tar.gz.asc[asc] /
https://downloads.apache.org/db/jdo/3.2.1/jdo-3.2.1-source-release.tar.gz.sha512[sha512]
| https://www.apache.org/dyn/closer.lua/db/jdo/3.2.1/jdo-3.2.1-source-release.zip[src.zip (2.8 MB)]
| https://downloads.apache.org/db/jdo/3.2.1/jdo-3.2.1-source-release.zip.asc[asc] /
https://downloads.apache.org/db/jdo/3.2.1/jdo-3.2.1-source-release.zip.sha512[sha512]

| https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12316653&styleName=Html&projectId=10630[3.2]
| 2022-02-01
| https://www.apache.org/dyn/closer.lua/db/jdo/3.2/jdo-3.2-source-release.tar.gz[src.tar.gz (1.1 MB)]
| https://downloads.apache.org/db/jdo/3.2/jdo-3.2-source-release.tar.gz.asc[asc] /
https://downloads.apache.org/db/jdo/3.2/jdo-3.2-source-release.tar.gz.sha512[sha512]
| https://www.apache.org/dyn/closer.lua/db/jdo/3.2/jdo-3.2-source-release.zip[src.zip (2.8 MB)]
| https://downloads.apache.org/db/jdo/3.2/jdo-3.2-source-release.zip.asc[asc] /
https://downloads.apache.org/db/jdo/3.2/jdo-3.2-source-release.zip.sha512[sha512]

|===


=== About JDO Releasesanchor:About_JDO_Releases[]

A release of JDO includes the JDO API and the Technology Compatibility
Kit (TCK). The TCK is available only in source form. The API project is
available as source and as a jar file using the standard Maven dependency protocol.

* The `jdo-api.jar` file is the only artifact needed for users who wish to compile their programs
using the JDO API. It can be downloaded from maven, or it can be built
manually from the source code.
* The TCK project contains the JDO Technology Compatibility Kit.

The 3.0.1 release has separate downloads for API and TCK sources. Newer distributions have all code in
in a single download.


=== Verifying Releasesanchor:Verifying_Releases[]

anchor:Verifying[]

It is essential that you verify the integrity of the downloaded files
using the PGP signature.

The PGP signatures can be verified using PGP or GPG. First download the
link:https://downloads.apache.org/db/jdo/KEYS[KEYS] as well as the `asc`
signature file for the particular distribution. Make sure you get these
files from the link:https://downloads.apache.org/db/jdo/[Apache downbload area], rather than from a mirror. Then verify the signatures using
these commands (depending on your tool set):

[source]
% pgpk -a KEYS
% pgpv release_artifact.asc

[source]
% pgp -ka KEYS
% pgp release_artifact.asc

[source]
% gpg --import KEYS
% gpg --verify release_artifact.asc
