:_basedir: 
:_imagesdir: images/
:grid: cols
:general:

[[index]]

== JDO Referencesanchor:JDO_References[]

=== Articlesanchor:Articles[]

There have been several articles about JDO on various websites. Some are
listed below

* SUN :
http://www.oracle.com/technetwork/java/index-jsp-135919.html[Oracle JDO
Web Site]
* TheServerSide.com :
http://www.theserverside.com/discussions/thread.tss?thread_id=771[discussion
on JDO and Entity Beans]
* TheServerSide.com :
http://www.theserverside.com/articles/article.tss?l=JDOQueryPart1[JDO 2
Queries - Methods, Paging, Unbound Variables]
* TheServerSide.com :
http://www.theserverside.com/articles/article.tss?l=JDOQueryPart2[JDO 2
Queries - Projections, Aggregates]
* DevX.com : http://www.devx.com/java/article/16373/[JDO brings DB
Programming into 21st Century Despite Controversy] by Dirk Bartels
* http://www.mainejug.org/jug/meetings/010829/index.htm[Java Data
Objects] by David Ezzio
* http://www-128.ibm.com/developerworks/db2/library/techarticle/dm-0506bhogal/[Introduction
to JDO2 using JPOX and DB2]
* http://db.apache.org/derby/integrate/JPOX_Derby.html[Using JPOX with
Apache Derby]

{empty} +


=== Booksanchor:Books[]

A number of books covering JDO are available. Some are listed below

* http://www.oreilly.com/catalog/jvadtaobj/[[.underline]#Java Data
Objects#] by Craig Russell and David Jordan. Publisher: O'Reilly
* http://www.phptr.com/bookstore/product.asp?isbn=0131407317&rl=1[[.underline]#Core
Java Data Objects#] by Sameer Tyagi, Michael Vorburger, Keiron McCammon,
Heiko Bobzin. Publisher: Prentice Hall

{empty} +


