:_basedir: 
:_imagesdir: images/
:grid: cols
:development:

[[index]]

== JDO 3.0.1 Distributionsanchor:JDO_3.0.1_Distributions[]

Use the links below to download Apache JDO from one of our mirrors. For
more information about the projects see link:downloads.html[Downloads].
For information on running the TCK, see link:tck.html[TCK].

It is good practice to xref:Verifying[verify the integrity] of the
distribution files.

You are currently using *http://apache.mirrors.nublue.co.uk/*. If you
encounter a problem with this mirror, then please select another. If all
mirrors are failing, there are backup mirrors at the end of the list.
See http://www.apache.org/mirrors/[status] of mirrors.

Other mirrors:

* http://apache.mirror.anlx.net/ 
* http://apache.mirrors.nublue.co.uk/ 
* http://mirror.ox.ac.uk/sites/rsync.apache.org/ 
* http://mirror.vorboss.net/apache/ 
* http://mirrors.ukfast.co.uk/sites/ftp.apache.org/ 
* http://www.mirrorservice.org/sites/ftp.apache.org/ 
* ftp://ftp.mirrorservice.org/sites/ftp.apache.org/ 
* https://www-eu.apache.org/dist/   (backup) 
* https://www-us.apache.org/dist/   (backup) 


{empty} +


=== Release Notesanchor:Release_Notes[]

https://issues.apache.org/jira/secure/ReleaseNote.jspa?version=12317950&styleName=Html&projectId=10630[View
release notes for JDO 3.0.1]

=== APIanchor:API[]

The api project contains source to build jdo-api.jar, which defines the
JDO API. The jar file is the only artifact needed for users who wish to
compile their programs using the JDO API. It can be downloaded
automatically by maven and placed into the local maven repository if you
include the proper dependency in your maven project definition. Use
groupId javax.jdo, artifactId jdo-api, version 3.0 and define your
remote repository as http://www.ibiblio.org/maven. Alternatively, it can
be downloaded manually and put into a location of your choice.

* http://people.apache.org/repo/m1-ibiblio-rsync-repository/javax.jdo/jars/jdo-api-3.0.1.jar[jdo-api-3.0.1.jar]
http://people.apache.org/repo/m1-ibiblio-rsync-repository/javax.jdo/jars/jdo-api-3.0.1.jar.asc[PGP]
http://people.apache.org/repo/m1-ibiblio-rsync-repository/javax.jdo/jars/jdo-api-3.0.1.jar.md5[MD5]

* http://people.apache.org/repo/m1-ibiblio-rsync-repository/javax.jdo/poms/jdo-api-3.0.1.pom[jdo-api-3.0.1.pom]
http://people.apache.org/repo/m1-ibiblio-rsync-repository/javax.jdo/poms/jdo-api-3.0.1.pom.asc[PGP]
http://people.apache.org/repo/m1-ibiblio-rsync-repository/javax.jdo/poms/jdo-api-3.0.1.pom.md5[MD5]

* http://apache.mirrors.nublue.co.uk//db/jdo/3.0.1/jdo-api-3.0.1-src.zip[jdo-api-3.0.1-src.zip]
http://www.apache.org/dist/db/jdo/3.0.1/jdo-api-3.0.1-src.zip.asc[PGP]
http://www.apache.org/dist/db/jdo/3.0.1/jdo-api-3.0.1-src.zip.md5[MD5]

* http://apache.mirrors.nublue.co.uk//db/jdo/3.0.1/jdo-api-3.0.1-src.tar.gz[jdo-api-3.0.1-src.tar.gz]
http://www.apache.org/dist/db/jdo/3.0.1/jdo-api-3.0.1-src.tar.gz.asc[PGP]
http://www.apache.org/dist/db/jdo/3.0.1/jdo-api-3.0.1-src.tar.gz.md5[MD5]

=== TCKanchor:TCK[]

This is a download for all implementors of JDO, and for those who want
to check how well an implementation is compliant with the JDO
specification. The tck2 project contains the JDO 2 Technology
Compatibility Kit. The source distribution is the only artifact needed
to be downloaded by the user. The dependencies (including the model20
jar, util20 jar, enhancer20 jar, api2 jar, and JPOX) are automatically
downloaded by maven as needed to run the TCK.

* http://apache.mirrors.nublue.co.uk//db/jdo/3.0.1/jdo-tck-3.0.1-src.zip[jdo-tck-3.0.1-src.zip]
http://www.apache.org/dist/db/jdo/3.0.1/jdo-tck-3.0.1-src.zip.asc[PGP]
http://www.apache.org/dist/db/jdo/3.0.1/jdo-tck-3.0.1-src.zip.md5[MD5]

* http://apache.mirrors.nublue.co.uk//db/jdo/3.0.1/jdo-tck-3.0.1-src.tar.gz[jdo-tck-3.0.1-src.tar.gz]
http://www.apache.org/dist/db/jdo/3.0.1/jdo-tck-3.0.1-src.tar.gz.asc[PGP]
http://www.apache.org/dist/db/jdo/3.0.1/jdo-tck-3.0.1-src.tar.gz.md5[MD5]

== Verifying Releasesanchor:Verifying_Releases[]

anchor:Verifying[]

It is essential that you verify the integrity of the downloaded files
using the PGP signature and/or the MD5 checksum. The checksum is not as
strong an indicator as the PGP signature is.

The PGP signatures can be verified using PGP or GPG. First download the
http://www.apache.org/dist/db/jdo/KEYS[KEYS] as well as the `asc`
signature file for the particular distribution. Make sure you get these
files from the http://www.apache.org/dist/db/jdo/[main distribution
directory], rather than from a mirror. Then verify the signatures using

` % pgpk -a KEYS % pgpv release_name.tar.gz.asc` _or_ +
` % pgp -ka KEYS % pgp release_name.tar.gz.asc` _or_ +
` % gpg --import KEYS % gpg --verify release_name.tar.gz.asc`

Alternatively, you can verify the checksums on the files. Unix programs
called `md5`/`sha1` or `md5sum`/`sha1sum` are included in many unix
distributions. `*sum` is also available as part of
http://www.gnu.org/software/textutils/textutils.html[GNU Textutils].
Windows users can get binary md5 programs from
http://www.fourmilab.ch/md5/[http://www.fourmilab.ch/md5] and
http://www.pc-tools.net/win32/freeware/console/[hhttp://www.pc-tools.net/win32/freeware/console].
Windows SlavaSoft http://www.slavasoft.com/fsum/[fsum] supports MD5 and
SHA1.

We highly recommend verifying the PGP signature, though.

'''''

