:_basedir: 
:_imagesdir: images/
:grid: cols
:development:

[[index]]

== JDO Source Codeanchor:JDO_Source_Code[]

=== Source Code Version Controlanchor:Source_Code_Version_Control[]

To receive notice of commits to the repository subscribe to
jdo-commits@db.apache.org by sending email to jdo-commits-subscribe@db.apache.org.

The ASF operates a dual hosting system for repositories that use https://git-scm.com[git] as their primary version
control system. This means committers may commit to either https://github.com/apache/db-jdo.git[GitHub] 
or https://gitbox.apache.org/repos/asf/db-jdo.git[gitbox.apache.org].
Changes are automatically mirrored to the other repository.

=== Checking Out Code

You can download the Apache JDO source code using:

....
git clone https://github.com/apache/db-jdo.git
....

Contributors can fork this repo using GitHub’s tools and contribute patches/new features using pull requests. See link:get-involved.html#_how_do_i_contribute_e_g_give_feedback_fix_bugs_etc[Getting Involved].

Committers can push to this repo directly, once their ASF account and GitHub account have been linked.
See https://gitbox.apache.org/setup[gitbox setup] for more details on how to do this.

=== Web Site

The sources for this site are available in a distinct repository that is also available on 
https://github.com/apache/db-jdo-site.git[GitHub] and https://gitbox.apache.org/repos/asf/db-jdo-site.git[gitbox.apache.org]:

....
git clone https://github.com/apache/db-jdo-site.git
....


=== Specification

The sources of the xref:specifications.adoc[JDO Specification] are available in a separate on https://github.com/clr-apache/jdo-specification.git[GitHub]:

....
git clone https://github.com/clr-apache/jdo-specification.git
....

