:_basedir: 
:_imagesdir: images/
:grid: cols
:general:

[[index]]

== About the Technology Compatibility Kitanchor:About_the_Technology_Compatibility_Kit[]

In order to demonstrate compliance with the Java Data Objects
specification, an implementation must pass all of the tests in the
Technology Compatibility Kit (TCK). The TCK is released as a packaged
Java source tree. Maven is the driver of a test run. You must download
and install http://maven.apache.org/[Maven 2+]before running the TCK.

=== Running the TCKanchor:Running_the_TCK[]

To run the Technology Compatibility Kit:

[arabic]
. Check out the JDO source code from the most recent branch. See
link:source-code.html[Source Code] for instructions on
checking out code.
. Follow the instructions in the Prerequisites section of
https://github.com/apache/db-jdo/blob/master/README.md[README.md]
. Follow the procedure in
https://github.com/apache/db-jdo/blob/master/tck/RunRules.md[RunRules.md]
in the tck directory.

=== Demonstrating Complianceanchor:Demonstrating_Compliance[]

Vendors must post test results on a publicly accessible web site for
examination by the public. The posting includes the output of the test
run, which consists of multiple log files containing configuration
information and test results. For an example of the required posting,
please see link:tck/final[http://db.apache.org/jdo/tck/final].

