# Staging and publishing profile for Apache JDO
# NOTE: This does currently not work, presumably because JDO is a sub project and there is 
#       no staging area for subprojects or for the parent 'db' project.
staging:
  profile: ~
  whoami:  staging
  subdir: content/jdo
 
publish:
  whoami:  master
  subdir:  content/jdo

github:
  description: "Apache JDO project"
  homepage: https://db.apache.org/jdo
  labels:
    - db
    - jdo
    - nosql
    - jpa
    - jta
    - api
    - database
    - orm
    - apache
    - java
