github:
  description: "Apache JDO project"
  homepage: https://db.apache.org/jdo
  labels:
    - db
    - jdo
    - nosql
    - jpa
    - jta
    - api
    - database
    - orm
    - apache
    - java

  # Set up branch protection for site publishing branch to avoid accidental deletion
  # Force-pushes are still necessary as they are used to deploy new versions of the site
  protected_branches:
    publish:
      allow_force_pushes: true
