github:
  description: "Apache JDO project"
  homepage: https://db.apache.org/jdo
  labels:
    - db
    - jdo
    - nosql
    - jpa
    - jta
    - api
    - database
    - orm
    - apache
    - java

  enabled_merge_buttons:
    # disable merge button:
    merge:   false
    # enable squash button:
    squash:  true
    # enable rebase button:
    rebase:  true

  protected_branches:
    # rules for the 'main' branch
    main:
      # disallows pushing merge commits to the branch
      required_linear_history: true

      required_status_checks:
        # strict means "Require branches to be up to date before merging".
        strict: false

    # rules for the 'publish' branch
    #
    # set up branch protection for site publishing branch to avoid accidental deletion
    # force-pushes are still necessary as they are used to deploy new versions of the site
    #publish:
    #  allow_force_pushes: true

  custom_subjects:
    # set custom subjects for automated mails for actions on GitHub
    new_pr: "[PR] {title} ({repository})"
    close_pr: "Re: [PR] {title} ({repository})"
    comment_pr: "Re: [PR] {title} ({repository})"
    merge_pr: "Re: [PR] {title} ({repository})"
    catchall: "Updated: {repository}/#{issue_id}: {title}"
    new_issue: "[I] {title} ({repository})"
    comment_issue: "Re: [I] {title} ({repository})"
    close_issue: "Re: [I] {title} ({repository})"
    catchall: "[GH] {title} ({repository})"
    new_discussion: "[D] {title} ({repository})"
    edit_discussion: "Re: [D] {title} ({repository})"
    close_discussion: "Re: [D] {title} ({repository})"
    close_discussion_with_comment: "Re: [D] {title} ({repository})"
    reopen_discussion: "Re: [D] {title} ({repository})"
    new_comment_discussion: "Re: [D] {title} ({repository})"
    edit_comment_discussion: "Re: [D] {title} ({repository})"
    delete_comment_discussion: "Re: [D] {title} ({repository})"


notifications:
  commits:      jdo-commits@db.apache.org
  issues:       jdo-dev@db.apache.org
  pullrequests: jdo-dev@db.apache.org
  jobs:         jdo-dev@db.apache.org
  discussions:  jdo-dev@db.apache.org
  jira_options: link label
