# Staging and publishing profile for Apache JDO:
staging:
  profile: ~
  whoami:  master
  outputdir: jdo
  subdir: jdo
 
publish:
  whoami:  publish
  outputdir:  jdo

github:
  description: "Apache JDO project"
  homepage: https://db.apache.org/jdo
  labels:
    - db
    - jdo
    - nosql
    - jpa
    - jta
    - api
    - database
    - orm
    - apache
    - java
